services:
  redis:
    image: redis:7-alpine
    container_name: festwear-redis
    ports:
      - "6379:6379"
    volumes:
      - festwear-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  festwear-redis-data:
